const phoneConst = {
  STORE_PHONES_DATA: 'STORE_PHONES_DATA',

  STORE_CURRENT_PHONE: 'STORE_CURRENT_PHONE',
  FREE_BUSY_NUMBER: 'FREE_BUSY_NUMBER',
  FREE_BUSY_IN_STORE: 'FREE_BUSY_IN_STORE',
  REQUEST_PHONE_NUMBER: 'REQUEST_PHONE_NUMBER',

  STORE_PHONE_DATA: 'STORE_PHONE_DATA',

  SEARCH_PHONE_NUMBER: 'SEARCH_PHONE_NUMBER',
  STORE_FIND_NUMBER: 'STORE_FIND_NUMBER',
  PHONE_FIND_FAILED: 'PHONE_FIND_FAILED',
  RESTORE_FIND_NUMBER: 'RESTORE_FIND_NUMBER',

  SAVE_FILTER_DATA: 'SAVE_FILTER_DATA',

  UPDATE_PHONE_DATA: 'UPDATE_PHONE_DATA',

  SHOW_DRIVE_DIALOG: 'SHOW_DRIVE_DIALOG',
  STORE_DIALOG_STATE: 'STORE_DIALOG_STATE',
  STORE_NOTY_MESSAGE: 'STORE_NOTY_MESSAGE',

  UPDATE_PHONE: 'UPDATE_PHONE'
}

export default { phoneConst }